### ISSUE TITLE
Integrate ACLs/RBAC

### ISSUE THREAD

**Issue by tboerger** [kleister/kleister-api#21]

**Comment by tboerger** [comment]
Partially integrated

**Comment by hsluoyz** [comment]
Hi @tboerger , [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I think it's a good choice if you want to implement ACL/RBAC security. Let me know if you have any questions:)
